---
- name: ensure the web dir links to the install dir
  file: src={{ piwigo_install_dir }}/piwigo
        dest={{ piwigo_webserver_dir }}
        state=link
  sudo: yes
  notify: restart webserver
  tags: piwigo

- name: ensure the piwigo apache site is installed
  template: src=site.conf.j2
            dest=/etc/apache2/sites-available/piwigo.conf
  sudo: yes
  notify: restart webserver
  tags: piwigo

- name: ensure the piwigo apache site is enabled
  file: src=/etc/apache2/sites-available/piwigo.conf
        dest=/etc/apache2/sites-enabled/piwigo.conf
        state=link
  sudo: yes
  notify: restart webserver
  tags: piwigo
